/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMBinaryReference = CIMBinaryReference1[];

/**
 * Represents a binary reference in a document.
 */
export interface CIMBinaryReference1 {
  /**
   * Gets or sets the URI of the binary reference. Typically set by the system but used as a reference path.
   */
  uri?: null | string;
  /**
   * Gets or sets the base64 encoded data of the binary reference.
   */
  data?: null | string;
  /**
   * Gets or sets the stored CIM object.
   */
  object?: null | CIMObject;
}
/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
