/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMBindVariable1 = CIMObject & {
  /**
   * Gets or sets the name of the variable. The name must be unique among all variables.
   */
  variableName?: null | string;
  /**
   * Gets or sets the alias of the variable.
   */
  alias?: null | string;
  /**
   * Gets or sets the type of the variable.
   */
  dataType?: BindVariableType;
};
/**
 * Bind variable types.
 */
export type BindVariableType = 0 | 1 | 2 | 3 | 4;
export type CIMBindVariable = CIMBindVariable1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
