/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a callout.
 */
export interface CIMCallout {
  /**
   * Gets or sets the leader tolerance which is the closest distance (in points) to the text the anchor point can be for the callout to draw.
   */
  leaderTolerance?: number;
  /**
   * Gets or sets the leader offset which is an offset value defining the distance (in points) between the anchor point and the beginning of the drawn leader.
   */
  leaderOffset?: number;
}
