/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Provides a type of coloring that chart series uses.
 */
export type ChartColorType = 0 | 1 | 2;
/**
 * Chart font weight types.
 */
export type ChartFontWeight = 0 | 1 | 2;
/**
 * Options for choosing text cases for charts.
 */
export type ChartTextCase = 0 | 1 | 2 | 3 | 4;
/**
 * Describes the different types of units.
 */
export type UnitType = 0 | 1 | 2 | 3;
/**
 * Describes the different types of geometry.
 */
export type GeometryType = 0 | 513 | 3077 | 3594 | 8710 | 25607 | 27656 | 32777;
/**
 * Visual variable info types.
 *
 */
export type ExpressionReturnType = 0 | 1 | 2;
/**
 * Chart line dash style.
 */
export type ChartLineDashStyle = 0 | 1 | 2 | 3 | 4 | 5;
/**
 * Chart legend alignment options.
 */
export type ChartLegendAlignment = 0 | 1 | 2 | 3;
/**
 * Specifies the position of the content for a target.
 */
export type ChartPosition = 0 | 1 | 2 | 3 | 4;
/**
 * Specifies the type of guide.
 */
export type ChartGuideType = 0 | 1;
/**
 * Specifies the type of value.
 */
export type ChartValueType = 0 | 1;
/**
 * Provides a choice of how map selection is processed in the chart.
 */
export type ChartMapSelectionHandling = 0 | 1 | 2;
export type CIMChart = CIMChart1[];

/**
 * Provides access to members that control chart properties.
 */
export interface CIMChart1 {
  /**
   * Gets or sets the name of the chart.
   */
  name?: null | string;
  /**
   * Gets or sets the series properties of the chart.
   */
  series?: CIMChartSeries[] | null;
  /**
   * Gets or sets the general properties of the chart.
   */
  generalProperties?: null | CIMChartGeneralProperties;
  /**
   * Gets or sets the legend properties of the chart.
   */
  legend?: null | CIMChartLegend;
  /**
   * Gets or sets the properties of chart axis.
   */
  axes?: CIMChartAxis[] | null;
  /**
   * Gets or sets a setting which indicates whether chart handles selection in the input layer by creating series only from the selected data or
   * highlights selected values on the chart made from entire dataset.
   */
  mapSelectionHandling?: ChartMapSelectionHandling;
  /**
   * Gets or sets the client metadata about the chart.
   */
  metaData?: null | string;
  /**
   * Gets or sets the multi series chart properties for supported chart types.
   */
  multiSeriesChartProperties?: null | CIMMultiSeriesChartProperties;
}
/**
 * Provides access to members that control chart series properties.
 */
export interface CIMChartSeries {
  /**
   * Gets or sets the name of the series shown in the legend.
   */
  name?: null | string;
  /**
   * Gets or sets the default and unique name of the series.
   */
  uniqueName?: null | string;
  /**
   * Gets or sets the data field names in the series. Optional depending on series type.
   */
  fields?: string[] | null;
  /**
   * Gets or sets the sort field names in the series.
   */
  orderFields?: string[] | null;
  /**
   * Gets or sets the group field names in the series.
   */
  groupFields?: string[] | null;
  /**
   * Gets or sets the format string for series value labels.
   */
  whereClause?: null | string;
  /**
   * Gets or sets a value indicating whether the series shows data labels.
   */
  showLabels?: boolean;
  /**
   * Gets or sets the index of horizontal axis.
   */
  horizontalAxis?: number;
  /**
   * Gets or sets the index of vertical axis.
   */
  verticalAxis?: number;
  /**
   * Gets or sets the type of color for the series.
   */
  colorType?: ChartColorType;
  /**
   * Gets or sets the aggregate field values if series data has a group field.
   * Allowed values are count, sum, median, mean, and empty string.
   */
  fieldAggregation?: string[] | null;
  /**
   * Gets or sets the array of sort order types for fields in OrderFields property
   * Allowed values 0(Ascending), 1(Descending).
   */
  orderFieldsSortTypes?: number[] | null;
  /**
   * Gets or sets a value indicating whether the series is visible or not.
   */
  visible?: boolean;
  /**
   * Gets or sets the text style for the data label.
   */
  dataLabelText?: null | CIMChartTextProperties;
  /**
   * Gets or sets a value indicating whether this series is a multi series.
   */
  multiSeries?: boolean;
  /**
   * Gets or sets the locations for which data is to be plotted.
   */
  locations?: CIMChartLocationDefinition[] | null;
}
/**
 * Represents chart text properties.
 *
 */
export interface CIMChartTextProperties {
  /**
   * Gets or sets the fill color for the font.
   */
  fontFillColor?: null | CIMColor;
  /**
   * Gets or sets the outline color for the font.
   */
  fontOutlineColor?: null | CIMColor;
  /**
   * Gets or sets the font family name.
   */
  fontFamilyName?: null | string;
  /**
   * Gets or sets a value indicating whether the font style if it is italic or not.
   */
  fontItalic?: boolean;
  /**
   * Gets or sets the font size in points.
   */
  fontSize?: number;
  /**
   * Gets or sets the font weight.
   */
  fontWeight?: ChartFontWeight;
  /**
   * Gets or sets the text case.
   */
  textCase?: ChartTextCase;
  /**
   * Gets or sets a value indicating whether the text is drawn with an underline.
   */
  textUnderline?: boolean;
  /**
   * Gets or sets a value indicating whether the text is drawn with a strikethrough.
   */
  textStrikethrough?: boolean;
  /**
   * Gets or sets a value indicating whether the text is drawn with an overline.
   */
  textOverline?: boolean;
}
/**
 * Supports colors in the CIM model by providing low level access to properties common amongst all color types.
 */
export interface CIMColor {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
}
/**
 * Supports colors spaces by providing a common base type for all color spaces.
 */
export interface CIMColorSpace {}
/**
 * Represents the definition of a location for which data is to be plotted.
 */
export interface CIMChartLocationDefinition {
  /**
   * Gets or sets the geometry.
   */
  geometry?: null | Geometry;
  /**
   * Gets or sets the symbol.
   */
  symbol?: null | CIMSymbolReference;
  /**
   * Gets or sets the label.
   */
  label?: null | string;
  /**
   * Gets or sets a value indicating whether this location is enabled or not.
   */
  enabled?: boolean;
}
/**
 * An abstract base class for objects that define geometric shapes. Geometry objects can be used
 * as geometry definitions for rendering data.
 */
export interface Geometry {
  /**
   * Gets a value indicating if the geometry has Z.
   */
  hasZ?: boolean;
  /**
   * Gets a value indicating if the geometry has M.
   */
  hasM?: boolean;
  /**
   * Gets a value indicating if the geometry has ID.
   */
  hasID?: boolean;
  /**
   * Gets the spatial reference of this instance.
   */
  spatialReference?: null | SpatialReference;
  /**
   * Gets the dimension of the geometry.
   */
  dimension?: number;
}
/**
 * Class representing a spatial reference.
 */
export interface SpatialReference {
  /**
   * Gets the well-known ID for this instance.
   */
  wkid?: number;
  /**
   * Gets the latest well-known ID for this instance.
   */
  latestWkid?: number;
  /**
   * Gets the underlying geographic coordinate system for this instance.
   * If this instance is a geographic coordinate system,
   * a pointer to this instance is returned.
   */
  gcs?: null | SpatialReference;
  /**
   * Gets the well-known text for this instance.
   */
  wkt?: null | string;
  /**
   * Gets the name of the spatial reference.
   */
  name?: null | string;
  /**
   * Gets the geographic coordinate system well-known ID.
   */
  gcsWkid?: number;
  /**
   * Gets the geographic coordinate system well-known text.
   */
  gcsWkt?: null | string;
  /**
   * Gets the vertical coordinate system well-known ID.
   */
  vcsWkid?: number;
  /**
   * Gets the vertical coordinate system well-known text.
   */
  vcsWkt?: null | string;
  /**
   * Determines if a vertical coordinate system has been defined.
   */
  hasVcs?: boolean;
  /**
   * Gets the XY Tolerance.
   */
  xyTolerance?: number;
  /**
   * Gets the XY Resolution.
   */
  xyResolution?: number;
  /**
   * Gets the Z Tolerance.
   */
  zTolerance?: number;
  /**
   * Gets the M Tolerance.
   */
  mTolerance?: number;
  /**
   * Gets the XY Scale.
   */
  xyScale?: number;
  /**
   * Gets the Z Scale.
   */
  zScale?: number;
  /**
   * Gets the M Scale.
   */
  mScale?: number;
  /**
   * Gets the false X.
   */
  falseX?: number;
  /**
   * Gets the false Y.
   */
  falseY?: number;
  /**
   * Gets the false Z.
   */
  falseZ?: number;
  /**
   * Gets the false M.
   */
  falseM?: number;
  /**
   * Gets the left longitude value of the geographic coordinate system.
   */
  leftLongitude?: number;
  /**
   * Gets the right longitude value of the geographic coordinate system.
   */
  rightLongitude?: number;
  /**
   * Gets the HighPrecision flag of this instance.
   */
  isHighPrecision?: boolean;
  /**
   * Gets the units that the spatial reference coordinates are in.
   */
  unit?: null | Unit;
  /**
   * Gets the units that the spatial reference z-coordinates are in.
   */
  zUnit?: null | Unit;
  /**
   * Gets the central meridian of the projected coordinate system.
   */
  centralMeridian?: number;
  /**
   * Gets if this is a geographic coordinate system.
   */
  isGeographic?: boolean;
  /**
   * Gets if this is a projected coordinate system.
   */
  isProjected?: boolean;
  /**
   * Gets if this is an image coordinate system.
   */
  isImage?: boolean;
  /**
   * Gets if this is the unknown coordinate system.
   */
  isUnknown?: boolean;
  /**
   * Gets if this is instance is pannable.
   */
  isPannable?: boolean;
  /**
   * Gets the square domain extent of the spatial reference.
   */
  domain?: null | Envelope;
  /**
   * Gets the horizontal datum of this spatial reference.
   */
  datum?: null | Datum;
}
/**
 * A common base class between all units, linear, area and angular units.
 */
export interface Unit {
  /**
   * Gets the well-known ID of the unit. If the unit is a custom unit, then the factory code will be 0.
   */
  factoryCode?: number;
  /**
   * Gets the well-known text of the unit.
   */
  wkt?: null | string;
  /**
   * Gets the name of the unit.
   */
  name?: null | string;
  /**
   * Gets the conversion factor of the unit.
   */
  conversionFactor?: number;
  /**
   * Gets the type of unit.
   */
  unitType?: UnitType;
}
/**
 * An envelope is an axis-aligned box described by the coordinates
 * of the lower left corner and the coordinates of the upper right corner.   To create an envelope use the
 * EnvelopeBuilderEx object.
 */
export interface Envelope {
  /**
   * Gets a value indicating if the geometry has Z.
   */
  hasZ?: boolean;
  /**
   * Gets a value indicating if the geometry has M.
   */
  hasM?: boolean;
  /**
   * Gets a value indicating if the geometry has ID.
   */
  hasID?: boolean;
  /**
   * Gets the spatial reference of this instance.
   */
  spatialReference?: null | SpatialReference;
  /**
   * Gets the dimension of the geometry.
   */
  dimension?: number;
  /**
   * Gets the GeometryType of this instance.  Always returns Envelope.
   */
  geometryType?: GeometryType;
  /**
   * Gets the point count of this instance. Always returns 5.
   */
  pointCount?: number;
  /**
   * Gets the X minimum of this instance.
   */
  xMin?: number;
  /**
   * Gets the Y minimum of this instance.
   */
  yMin?: number;
  /**
   * Gets the X maximum of this instance.
   */
  xMax?: number;
  /**
   * Gets the Y maximum of this instance.
   */
  yMax?: number;
  /**
   * Gets the Z minimum of this instance.
   */
  zMin?: number;
  /**
   * Gets the Z maximum of this instance.
   */
  zMax?: number;
  /**
   * Gets the M minimum of this instance.
   */
  mMin?: number;
  /**
   * Gets the M maximum of this instance.
   */
  mMax?: number;
  /**
   * Gets the ID minimum of this instance.
   */
  idMin?: number;
  /**
   * Gets the ID maximum of this instance.
   */
  idMax?: number;
  /**
   * Gets the center of this instance as a Coordinate2D.
   */
  centerCoordinate?: Coordinate2D;
  /**
   * Gets the center of this instance as a MapPoint.
   */
  center?: null | MapPoint;
  /**
   * Gets the height of this instance.
   */
  height?: number;
  /**
   * Gets the width of this instance.
   */
  width?: number;
  /**
   * Gets the depth of this instance.
   */
  depth?: number;
  /**
   * Gets the perimeter length of this instance.
   */
  length?: number;
  /**
   * Gets the 3D length of the perimeter of this instance.
   */
  length3D?: number;
  /**
   * Gets the area of this instance.
   */
  area?: number;
  /**
   * Gets the minimum enclosing envelope of this instance. Returns null if this geometry has IsEmpty = true.
   */
  extent?: null | Envelope;
  /**
   * Gets a value indicating whether or not the geometry is empty.
   */
  isEmpty?: boolean;
}
/**
 * A lightweight structure that holds X and Y values.
 */
export interface Coordinate2D {
  /**
   * Gets or sets the X-component.
   */
  x?: number;
  /**
   * Gets or sets the Y-component.
   */
  y?: number;
  /**
   * Gets or sets the length of the Coordinate2D as a vector.
   */
  magnitude?: number;
  /**
   * Indicates if the Coordinate2D is empty.
   */
  isEmpty?: boolean;
}
/**
 * A MapPoint represents a single location in space. The location consists of X and Y values and optionally a Z and/or M value.
 * To create a MapPoint use the MapPointBuilderEx object.
 */
export interface MapPoint {
  /**
   * Gets a value indicating if the geometry has Z.
   */
  hasZ?: boolean;
  /**
   * Gets a value indicating if the geometry has M.
   */
  hasM?: boolean;
  /**
   * Gets a value indicating if the geometry has ID.
   */
  hasID?: boolean;
  /**
   * Gets the spatial reference of this instance.
   */
  spatialReference?: null | SpatialReference;
  /**
   * Gets the dimension of the geometry.
   */
  dimension?: number;
  /**
   * Gets the GeometryType of this instance.  Always returns Point.
   */
  geometryType?: GeometryType;
  /**
   * Gets the point count of the geometry. This is always 1.
   */
  pointCount?: number;
  /**
   * Gets the X-coordinate.
   */
  x?: number;
  /**
   * Gets the Y-coordinate.
   */
  y?: number;
  /**
   * Gets the Z-coordinate.
   */
  z?: number;
  /**
   * Gets the measure value.
   */
  m?: number;
  /**
   * Gets the ID value.
   */
  id?: number;
  /**
   * Gets a Coordinate2D structure with the X and Y values.
   */
  coordinate2D?: Coordinate2D;
  /**
   * Gets a Coordinate3D structure with the X, Y, and Z values.
   */
  coordinate3D?: Coordinate3D;
  /**
   * Gets the minimum enclosing envelope of the geometry.
   */
  extent?: null | Envelope;
  /**
   * Gets a value indicating whether or not the geometry is empty.
   */
  isEmpty?: boolean;
}
/**
 * A structure containing methods to manipulate 3D vertices and 3D vectors.
 */
export interface Coordinate3D {
  /**
   * Gets or sets the X-component.
   */
  x?: number;
  /**
   * Gets or sets the Y-component.
   */
  y?: number;
  /**
   * Gets or sets the Z-component.
   */
  z?: number;
  /**
   * Gets or sets the length of the Coordinate3D as a vector.
   */
  magnitude?: number;
  /**
   * Gets the inclination of the Coordinate3D. The inclination is measured in radians.
   */
  inclination?: number;
  /**
   * Gets the azimuth of the Coordinate3D. The azimuth is measured in radians.
   */
  azimuth?: number;
  /**
   * Indicates if the Coordinate3D is empty.
   */
  isEmpty?: boolean;
}
/**
 * Describes the horizontal datum of a geographic coordinate system. It is returned from Datum.
 */
export interface Datum {
  /**
   * Gets the well-known ID of this horizontal datum.
   */
  wkid?: number;
  /**
   * Gets the well-known ID of the spheroid of this horizontal datum.
   */
  spheroidWkid?: number;
  /**
   * Gets the length of the semi-major axis of the spheroid of this horizontal datum.
   */
  spheroidSemiMajorAxis?: number;
  /**
   * Gets the length of the semi-minor axis of the spheroid of this horizontal datum.
   */
  spheroidSemiMinorAxis?: number;
  /**
   * Gets the flattening ratio of the spheroid of this horizontal datum.
   */
  spheroidFlattening?: number;
  /**
   * Gets the name of this horizontal datum.
   */
  name?: null | string;
  /**
   * Gets the name of the spheroid of this horizontal datum.
   */
  spheroidName?: null | string;
}
/**
 * Represents a symbol reference.
 *
 */
export interface CIMSymbolReference {
  /**
   * Gets or sets the primitive overrides. Typically set by renderers at draw time.
   */
  primitiveOverrides?: CIMPrimitiveOverride[] | null;
  /**
   * Gets or sets the style path. Reserved for future use.
   */
  stylePath?: null | string;
  /**
   * Gets or sets the symbol.
   */
  symbol?: null | CIMSymbol;
  /**
   * Gets or sets the symbol name.
   */
  symbolName?: null | string;
  /**
   * Gets or sets the minimum scale range the symbol reference should be displayed at.
   */
  minScale?: number;
  /**
   * Gets or sets the maximum scale range the symbol reference should be displayed at.
   */
  maxScale?: number;
  /**
   * Gets or sets an array of scale dependent sizes.
   */
  scaleDependentSizeVariation?: CIMScaleDependentSizeVariation[] | null;
  /**
   * Gets or sets the minimum distance at which symbols are visible. Objects closer than this don't get rendered.
   */
  minDistance?: number;
  /**
   * Gets or sets the maximum distance at which symbols are visible. Objects beyond this point don't get rendered.
   */
  maxDistance?: number;
}
/**
 * Represents a primitive override.
 *
 */
export interface CIMPrimitiveOverride {
  /**
   * Gets or sets the primitive name this override applies to.
   */
  primitiveName?: null | string;
  /**
   * Gets or sets the property name in the primitive this override applies to.
   */
  propertyName?: null | string;
  /**
   * Gets or sets the expression.
   */
  expression?: null | string;
  /**
   * Gets or sets ExpressionInfo that contains the Arcade expression that returns value as a number or a string depending on the PropertyName.
   */
  valueExpressionInfo?: null | CIMExpressionInfo;
}
/**
 * Represents the properties required for authoring an Arcade expression.
 */
export interface CIMExpressionInfo {
  /**
   * Gets or sets the human readable text that describes the expression.
   */
  title?: null | string;
  /**
   * Gets or sets the Arcade expression used to evaluate and return the value that a property expects.
   */
  expression?: null | string;
  /**
   * Gets or sets the Name of the expression.
   */
  name?: null | string;
  /**
   * Gets or sets the ReturnType of the expression.
   */
  returnType?: ExpressionReturnType;
}
/**
 * Represents a symbol. A symbol is used to describe how a geometric shape, such as that from a graphic or feature, is displayed.
 *
 */
export interface CIMSymbol {}
/**
 * Represents the scale dependent size variations for a symbol reference.
 *
 */
export interface CIMScaleDependentSizeVariation {
  /**
   * Gets or sets the scale the size is associated with.
   */
  scale?: number;
  /**
   * Gets or sets the size for the associated scale.
   */
  size?: number;
}
/**
 * Provides access to members that control general chart properties.
 */
export interface CIMChartGeneralProperties {
  /**
   * Gets or sets the title of the chart.
   */
  title?: null | string;
  /**
   * Gets or sets a value indicating whether the chart title is visible.
   */
  showTitle?: boolean;
  /**
   * Gets or sets a value indicating whether the chart title is auto generated.
   */
  useAutomaticTitle?: boolean;
  /**
   * Gets or sets the subtitle of the chart.
   */
  subTitle?: null | string;
  /**
   * Gets or sets a value indicating whether the chart subtitle is visible.
   */
  showSubTitle?: boolean;
  /**
   * Gets or sets the footer of the chart.
   */
  footer?: null | string;
  /**
   * Gets or sets a value indicating whether the chart footer is visible.
   */
  showFooter?: boolean;
  /**
   * Gets or sets the theme of the chart.
   */
  theme?: null | string;
  /**
   * Gets or sets the title symbol properties.
   */
  titleText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the subtitle symbol properties.
   */
  subTitleText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the footer symbol properties.
   */
  footerText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the background fill symbol properties for the chart.
   */
  backgroundSymbolProperties?: null | CIMChartFillSymbolProperties;
  /**
   * Gets or sets the line symbol properties for grid lines.
   */
  gridLineSymbolProperties?: null | CIMChartLineSymbolProperties;
}
/**
 * Provides access to members that control properties of the fill
 * symbol.
 */
export interface CIMChartFillSymbolProperties {
  /**
   * Gets or sets the color of the fill.
   */
  color?: null | CIMColor;
  /**
   * Gets or sets the transparency level of histogram bars.
   */
  opacity?: number;
  /**
   * Gets or sets the properties of the fill symbol border.
   */
  lineSymbolProperties?: null | CIMChartLineSymbolProperties;
}
/**
 * Provides access to members that control properties of the line
 * symbol.
 */
export interface CIMChartLineSymbolProperties {
  /**
   * Gets or sets a value indicating whether the line is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets the width of the line.
   */
  width?: number;
  /**
   * Gets or sets the style of the line.
   */
  style?: ChartLineDashStyle;
  /**
   * Gets or sets the color of the line.
   */
  color?: null | CIMColor;
}
/**
 * Provides access to members that control chart legend properties.
 */
export interface CIMChartLegend {
  /**
   * Gets or sets a value indicating whether the chart legend is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets the title of the legend.
   */
  title?: null | string;
  /**
   * Gets or sets a value indicating whether the legend title is visible.
   */
  showTitle?: boolean;
  /**
   * Gets or sets the options in arranging the chart legend.
   */
  alignment?: ChartLegendAlignment;
  /**
   * Gets or sets the format string for series value labels.
   */
  valueFormat?: null | string;
  /**
   * Gets or sets the text symbol properties.
   */
  legendText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the text symbol properties for legend title.
   */
  legendTitle?: null | CIMChartTextProperties;
}
/**
 * Provides access to members that control chart axis properties.
 */
export interface CIMChartAxis {
  /**
   * Gets or sets a value indicating whether the chart axis is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets a value indicating whether the chart axis has logarithmic scale.
   */
  isLogarithmic?: boolean;
  /**
   * Gets or sets the title of an axis.
   */
  title?: null | string;
  /**
   * Gets or sets a value indicating whether the axis title is visible.
   */
  showTitle?: boolean;
  /**
   * Gets or sets a value indicating whether the axis title is auto generated.
   */
  useAutomaticTitle?: boolean;
  /**
   * Gets or sets the format string for axis value labels.
   */
  valueFormat?: null | string;
  /**
   * Gets or sets the number format of the axis labels. ValueNumberFormat takes precedence over ValueFormat when both are specified.
   */
  valueNumberFormat?: null | CIMNumberFormat;
  /**
   * Gets or sets the format string for axis date/time labels.
   */
  dateTimeFormat?: null | string;
  /**
   * Gets or sets a value indicating whether the chart axis calculates its minimum.
   */
  calculateAutomaticMinimum?: boolean;
  /**
   * Gets or sets a value indicating whether the chart axis calculates its maximum.
   */
  calculateAutomaticMaximum?: boolean;
  minimum?: unknown;
  maximum?: unknown;
  /**
   * Gets or sets the title symbol properties.
   */
  titleText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the label symbol properties.
   */
  labelText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the line symbol properties for axis.
   */
  axisLineSymbolProperties?: null | CIMChartLineSymbolProperties;
  /**
   * Gets or sets the array of guides.
   */
  guides?: CIMChartGuide[] | null;
  /**
   * Gets or sets the character limit for axis labels.
   */
  labelCharacterLimit?: number;
  /**
   * Gets or sets the relative start position for zoom/pan navigation. The value range is normalized between 0 and 1.
   */
  zoomStartPosition?: number;
  /**
   * Gets or sets the relative end position for zoom/pan navigation. The value range is normalized between 0 and 1.
   */
  zoomEndPosition?: number;
}
/**
 * Represents a number format.
 *
 */
export interface CIMNumberFormat {}
/**
 * Define the properties to define a chart guide.
 */
export interface CIMChartGuide {
  /**
   * Gets or sets the name / title for the guide.
   */
  name?: null | string;
  /**
   * Gets or sets the label for the guide.
   */
  label?: null | string;
  /**
   * Gets or sets the text format for the guide label.
   */
  labelText?: null | CIMChartTextProperties;
  /**
   * Gets or sets the relative position of the label to the guide.
   */
  labelPosition?: ChartPosition;
  /**
   * Gets or sets the numeric coordinate of the from value for the guide. This value will be used when guide value type is set to numeric.
   */
  valueFrom?: number;
  /**
   * Gets or sets the numeric coordinate of the to value for the guide. This value will be used when guide value type is set to numeric.
   */
  valueTo?: number;
  /**
   * Gets or sets the temporal coordinate of the from value for the guide. This value will be used when guide value type is set to temporal.
   */
  timeFrom?: null | TimeInstant;
  /**
   * Gets or sets the temporal coordinate of the to value for the guide. This value will be used when guide value type is set to temporal.
   */
  timeTo?: null | TimeInstant;
  /**
   * Gets or sets a value indicating whether the guide is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets the type of the guide.
   */
  guideType?: ChartGuideType;
  /**
   * Gets or sets the type of the coordinate value used in the guide.
   */
  guideValueType?: ChartValueType;
  /**
   * Gets or sets the symbol properties for the guide.
   */
  fillSymbolProperties?: null | CIMChartFillSymbolProperties;
}
/**
 * Represents an instant in time. The time has no duration.
 */
export interface TimeInstant {
  /**
   * Gets or sets the time zone definition of the time.
   */
  timeReference?: null | TimeReference;
  /**
   * Gets or sets the time.
   */
  time?: string;
}
/**
 * Represents the time zone definition for a given date and time.
 */
export interface TimeReference {
  /**
   * Gets or sets the windows id for the time zone.
   */
  timeZoneNameID?: null | string;
  /**
   * Gets or sets a value indicating if the time reference should honor daylight savings time.
   */
  respectsDaylightSavingTime?: boolean;
  /**
   * Gets or sets a value indicating if the time reference should respect dynamic rules for adjusting with daylight savings time for specific years.
   */
  respectsDynamicAdjustmentRules?: boolean;
}
/**
 * Provides access to members that control multi series chart properties.
 */
export interface CIMMultiSeriesChartProperties {
  /**
   * Gets or sets a value indicating whether multi series chart properties are enabled.
   */
  enabled?: boolean;
}
