/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMColorModulationInfo = CIMObject & {
  /**
   * Gets or sets the attribute to use as a source for the color modulation.
   */
  field?: null | string;
  /**
   * Gets or sets the minimum value to compute modulation on linear scale based on field value.
   */
  minValue?: number;
  /**
   * Gets or sets the maximum value to compute modulation on linear scale based on field value.
   */
  maxValue?: number;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
