/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMDisplayFilter1 = CIMObject & {
  /**
   * Gets or sets the name of the display filter.
   */
  name?: null | string;
  /**
   * Gets or sets the where clause that filters features for a given scale range.
   */
  whereClause?: null | string;
  /**
   * Gets or sets the minimum scale for this display filter.
   */
  minScale?: number;
  /**
   * Gets or sets the maximum scale for this display filter.
   */
  maxScale?: number;
};
export type CIMDisplayFilter = CIMDisplayFilter1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
