/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMDefinitionFilter1 = CIMObject & {
  /**
   * Gets or sets the name of the Definition Filter item.
   */
  name?: null | string;
  /**
   * Gets or sets the definition expression to filter features in the dataset.
   */
  definitionExpression?: null | string;
};
export type CIMDefinitionFilter = CIMDefinitionFilter1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
