/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMEditingTemplate1 = CIMObject & {
  /**
   * Gets or sets the description.
   */
  description?: null | string;
  /**
   * Gets or sets the name.
   */
  name?: null | string;
  /**
   * Gets or sets the tags.
   */
  tags?: null | string;
  /**
   * Gets or sets the default tool GUID.
   */
  defaultToolGUID?: null | string;
  /**
   * Gets or sets the excluded tool GUIDs.
   */
  excludedToolGUIDs?: string[] | null;
  /**
   * Gets or sets the per-tool options.
   */
  toolOptions?: CIMEditingTemplateToolOptions[] | null;
};
export type CIMEditingTemplateToolOptions = CIMObject & {
  /**
   * Gets or sets the tool ProgID.
   */
  toolProgID?: null | string;
  /**
   * Gets or sets the options for the specified creation tool.
   */
  options?: null | {
    [k: string]: unknown;
  };
};
export type CIMEditingTemplate = CIMEditingTemplate1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
