/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMEditingTemplateCollectionItem = CIMEditingTemplateCollectionItem1[];

/**
 * Represents an item that can be stored within an editing template collection.
 */
export interface CIMEditingTemplateCollectionItem1 {
  /**
   * Gets or sets the name of this item.
   */
  name?: null | string;
}
