/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a collection of editing templates.
 */
export interface CIMEditingTemplateCollection {
  /**
   * Gets or sets the name of this item.
   */
  name?: null | string;
  /**
   * Gets or sets the array of items stored within this collection.
   */
  contents?: CIMEditingTemplateCollectionItem[] | null;
  /**
   * Gets or sets a value indicating whether this collection is expanded in the user interface.
   */
  expanded?: boolean;
}
/**
 * Represents an item that can be stored within an editing template collection.
 */
export interface CIMEditingTemplateCollectionItem {
  /**
   * Gets or sets the name of this item.
   */
  name?: null | string;
}
