/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMEditingTemplateCollection = CIMEditingTemplateCollectionItem & {
  /**
   * Gets or sets the array of items stored within this collection.
   */
  contents?: CIMEditingTemplateCollectionItem[] | null;
  /**
   * Gets or sets a value indicating whether this collection is expanded in the user interface.
   */
  expanded?: boolean;
};
export type CIMEditingTemplateCollectionItem = CIMObject & {
  /**
   * Gets or sets the name of this item.
   */
  name?: null | string;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
