/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMEditingTemplateCollectionItem1 = CIMObject & {
  /**
   * Gets or sets the name of this item.
   */
  name?: null | string;
};
export type CIMEditingTemplateCollectionItem = CIMEditingTemplateCollectionItem1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
