/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Field search modes.
 *
 */
export type DataSearchMode = 0 | 1;
export type CIMFieldDescription = CIMFieldDescription1[];

/**
 * Represents a field description.
 *
 */
export interface CIMFieldDescription1 {
  /**
   * Gets or sets the field alias.
   */
  alias?: null | string;
  /**
   * Gets or sets the field name.
   */
  fieldName?: null | string;
  /**
   * Gets or sets a value indicating whether the field is highlighted.
   */
  highlight?: boolean;
  /**
   * Gets or sets the number format.
   */
  numberFormat?: null | CIMNumberFormat;
  /**
   * Gets or sets a value indicating whether the field is read only.
   */
  readOnly?: boolean;
  /**
   * Gets or sets a value indicating whether the field is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets a value indicating whether the field value is a ratio (used only by geoprocessing).
   */
  valueAsRatio?: boolean;
  /**
   * Gets or sets a value indicating whether the values from this field should be included in the search.
   */
  searchable?: boolean;
  /**
   * Gets or sets search mode to use when searching for values in this field.
   */
  searchMode?: DataSearchMode;
}
/**
 * Represents a number format.
 *
 */
export interface CIMNumberFormat {}
