/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMFieldMapping1 = CIMObject & {
  /**
   * Gets or sets the URI of the source layer or table.
   */
  sourceURI?: null | string;
  /**
   * Gets or sets the URI of the target layer or table.
   */
  targetURI?: null | string;
  /**
   * Gets or sets the expression for mapping from source layer or table to target layer or table.
   */
  mappingExpressionInfo?: null | CIMExpressionInfo;
};
export type CIMExpressionInfo = CIMObject & {
  /**
   * Gets or sets the human readable text that describes the expression.
   */
  title?: null | string;
  /**
   * Gets or sets the Arcade expression used to evaluate and return the value that a property expects.
   */
  expression?: null | string;
  /**
   * Gets or sets the Name of the expression.
   */
  name?: null | string;
  /**
   * Gets or sets the ReturnType of the expression.
   */
  returnType?: ExpressionReturnType;
};
/**
 * Visual variable info types.
 *
 */
export type ExpressionReturnType = 0 | 1 | 2;
export type CIMFieldMapping = CIMFieldMapping1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
