/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMFontVariation1 = CIMObject & {
  /**
   * Gets or sets the font variation tag name. This is a four letter identifier for a particular axis of variation, specified in the font.
   */
  tagName?: null | string;
  /**
   * Gets or sets the numeric value representing a particular font variation value.
   */
  value?: number;
};
export type CIMFontVariation = CIMFontVariation1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
