/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A list of orientation values.
 */
export type Orientation = 0 | 1;
export type CIMGuide = CIMGuide1[];

/**
 * Represents a guide used to snap elements on a page layout.
 */
export interface CIMGuide1 {
  /**
   * Gets or sets the position of the guide.
   */
  position?: number;
  /**
   * Gets or sets the horizontal or vertical orientation of the guide.
   */
  orientation?: Orientation;
}
