/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMGeometricEffect1 = CIMObject & {
  /**
   * Gets or sets the primitive name.
   */
  primitiveName?: null | string;
};
export type CIMGeometricEffect = CIMGeometricEffect1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
