/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMGuide1 = CIMObject & {
  /**
   * Gets or sets the position of the guide.
   */
  position?: number;
  /**
   * Gets or sets the horizontal or vertical orientation of the guide.
   */
  orientation?: Orientation;
};
/**
 * A list of orientation values.
 */
export type Orientation = 0 | 1;
export type CIMGuide = CIMGuide1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
