/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents general placement properties. This is base class for general placement properties for each label engine.
 *
 */
export interface CIMGeneralPlacementProperties {
  /**
   * Gets or sets a value indicating whether or not to draw unplaced labels.
   */
  drawUnplacedLabels?: boolean;
  /**
   * Gets or sets the inverted label tolerance which is the angle at which the label orientation is switched.
   */
  invertedLabelTolerance?: number;
  /**
   * Gets or sets a value indicating whether or not rotate labels when the display rotates.
   */
  rotateLabelWithDisplay?: boolean;
  /**
   * Gets or sets the unplaced label color.
   */
  unplacedLabelColor?: null | CIMColor;
}
/**
 * Supports colors in the CIM model by providing low level access to properties common amongst all color types.
 */
export interface CIMColor {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
}
/**
 * Supports colors spaces by providing a common base type for all color spaces.
 */
export interface CIMColorSpace {}
