/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMGeneralPlacementProperties = CIMObject & {
  /**
   * Gets or sets a value indicating whether or not to draw unplaced labels.
   */
  drawUnplacedLabels?: boolean;
  /**
   * Gets or sets the inverted label tolerance which is the angle at which the label orientation is switched.
   */
  invertedLabelTolerance?: number;
  /**
   * Gets or sets a value indicating whether or not rotate labels when the display rotates.
   */
  rotateLabelWithDisplay?: boolean;
  /**
   * Gets or sets the unplaced label color.
   */
  unplacedLabelColor?: null | CIMColor;
};
export type CIMColor = CIMObject & {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
};
export type CIMColorSpace = CIMObject;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
