/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * HTML pop-up styles.
 *
 */
export type HtmlPopupStyle = 0 | 1 | 2;

/**
 * Represents an HTML pop-up format.
 *
 */
export interface CIMHtmlPopupFormat {
  /**
   * Gets or sets the redirect field.
   */
  htmlRedirectField?: null | string;
  /**
   * Gets or sets the redirect field prefix.
   */
  htmlRedirectFieldPrefix?: null | string;
  /**
   * Gets or sets the redirect field suffix.
   */
  htmlRedirectFieldSuffix?: null | string;
  /**
   * Gets or sets the XSL style sheet.
   */
  htmlXSLStyleSheet?: null | string;
  /**
   * Gets or sets a value indicating whether of not to hide the field name column.
   */
  htmlHideFieldNameColumn?: boolean;
  /**
   * Gets or sets a value indicating whether of not to use coded domain values.
   */
  htmlUseCodedDomainValues?: boolean;
  /**
   * Gets or sets the presentation style.
   */
  htmlPresentationStyle?: HtmlPopupStyle;
}
