/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a KML data connection.
 *
 */
export interface CIMKMLDataConnection {
  /**
   * Gets or sets vendor specific parameters.
   */
  customParameters?: CIMStringMap[] | null;
  /**
   * Gets or sets the URI of the KML file or resource.
   */
  kmluri?: null | string;
}
/**
 * Represents a string map of key value pairs.
 *
 */
export interface CIMStringMap {
  /**
   * Gets or sets the key.
   */
  key?: null | string;
  /**
   * Gets or sets the value.
   */
  value?: null | string;
}
