/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Field types.
 */
export type EsriFieldType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13;

/**
 * Represents a Knowledge Graph Investigation.
 */
export interface CIMKnowledgeGraphInvestigation {
  /**
   * Gets or sets the name.
   */
  name?: null | string;
  /**
   * Gets or sets the URI of the definition. Typically set by the system and used as an identifier.
   */
  uri?: null | string;
  /**
   * Gets or sets the source URI of the item. Set if sourced from an external item such as an item on a portal.
   */
  sourceURI?: null | string;
  /**
   * Gets or sets the time the source was last modified, as of the last sync. Used to detect when another sync is needed.
   */
  sourceModifiedTime?: null | TimeInstant;
  /**
   * Gets or sets the metadata URI.
   */
  metadataURI?: null | string;
  /**
   * Gets or sets a value indicating whether the CIM definition accesses metadata from its data source (the default behavior), or if it has its own metadata stored in the project.
   */
  useSourceMetadata?: boolean;
  /**
   * Gets or sets the source portal URI of the item. Set if sourced from an external item such as an item on a portal.
   */
  sourcePortalUrl?: null | string;
  /**
   * Gets or sets the data connection.
   */
  dataConnection?: null | CIMDataConnection;
  /**
   * Gets or sets the array of Data Loading Configurations referenced by this Investigation.
   * All configurations are expected to have unique names.
   */
  dataLoadingConfigurations?: CIMKnowledgeGraphDataLoadingConfiguration[] | null;
}
/**
 * Represents an instant in time. The time has no duration.
 */
export interface TimeInstant {
  /**
   * Gets or sets the time zone definition of the time.
   */
  timeReference?: null | TimeReference;
  /**
   * Gets or sets the time.
   */
  time?: string;
}
/**
 * Represents the time zone definition for a given date and time.
 */
export interface TimeReference {
  /**
   * Gets or sets the windows id for the time zone.
   */
  timeZoneNameID?: null | string;
  /**
   * Gets or sets a value indicating if the time reference should honor daylight savings time.
   */
  respectsDaylightSavingTime?: boolean;
  /**
   * Gets or sets a value indicating if the time reference should respect dynamic rules for adjusting with daylight savings time for specific years.
   */
  respectsDynamicAdjustmentRules?: boolean;
}
/**
 * Represents a data connection.
 */
export interface CIMDataConnection {}
/**
 * Represents a Knowledge Graph Data Loading Configuration.
 */
export interface CIMKnowledgeGraphDataLoadingConfiguration {
  /**
   * Gets or sets the name of the Data Loading Configuration.
   * Names are expected to be unique within an Investigation.
   */
  name?: null | string;
  /**
   * Gets or sets the entities.
   */
  entities?: CIMKnowledgeGraphDataLoadingEntity[] | null;
  /**
   * Gets or sets the relationships.
   */
  relationships?: CIMKnowledgeGraphDataLoadingRelationship[] | null;
}
/**
 * Represents a Knowledge Graph Data Loading Entity.
 */
export interface CIMKnowledgeGraphDataLoadingEntity {
  /**
   * Gets or sets the name of the entity.
   */
  name?: null | string;
  /**
   * Gets or sets the type of the entity.
   */
  entityType?: null | string;
  /**
   * Gets or sets a value indicating whether the Type property
   * is a name itself or the name of a field.
   */
  typeIsFieldName?: boolean;
  /**
   * Gets or sets the properties of this entity.
   */
  properties?: CIMKnowledgeGraphProperty[] | null;
  /**
   * Gets or sets a value indicating whether this entity should be merged.
   */
  merge?: boolean;
}
/**
 * Represents a Knowledge Graph Data Loading Property used for entities and relationships.
 */
export interface CIMKnowledgeGraphProperty {
  /**
   * Gets or sets the name of the property.
   */
  name?: null | string;
  /**
   * Gets or sets the type of the property.
   */
  propertyType?: EsriFieldType;
  /**
   * Gets or sets the value which is to be imported.
   * Value will have to be tested for type in order to properly perform the import.
   */
  value?: null | CIMKnowledgeGraphPropertyValue;
  /**
   * Gets or sets a value indicating whether this property should be used
   * to determine a merge.
   */
  merge?: boolean;
}
/**
 * Base (indicator) class for all CIMKnowledgeGraphXXXPropertyValue.
 */
export interface CIMKnowledgeGraphPropertyValue {}
/**
 * Represents a Knowledge Graph Data Loading Relationship.
 */
export interface CIMKnowledgeGraphDataLoadingRelationship {
  /**
   * Gets or sets the source entity name.
   */
  sourceEntityName?: null | string;
  /**
   * Gets or sets the type of the relationship.
   */
  relationshipType?: null | string;
  /**
   * Gets or sets a value indicating whether the Type property
   * is a name itself or the name of a field.
   */
  typeIsFieldName?: boolean;
  /**
   * Gets or sets the target entity name.
   */
  targetEntityName?: null | string;
  /**
   * Gets or sets the properties of this relationship.
   */
  properties?: CIMKnowledgeGraphProperty[] | null;
  /**
   * Gets or sets a value indicating whether this relationship should be merged.
   */
  merge?: boolean;
}
