/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMLocator1 = CIMObject & {
  /**
   * Gets or sets the type of locator for the LocatorURI specified.
   */
  locatorType?: LocatorType;
  /**
   * Gets or sets the name of the locator.
   */
  name?: null | string;
  /**
   * Gets or sets locator source URI. It can either be a local path, URL or a layer URI from this map. e.g. file://<folder_path>,  http://<url>, CIMPATH=<cim_layer_UR>.
   */
  locatorURI?: null | string;
  /**
   * Gets or sets a value indicating whether or not to suggestions should enabled if the locator supports suggestions.
   */
  suggestionsEnabled?: boolean;
  /**
   * Gets or sets a value indicating whether or not to this locator is enabled.
   */
  enabled?: boolean;
  /**
   * Gets or sets a value indicating whether the locator supports suggestions.
   */
  suggestionsSupported?: boolean;
};
/**
 * Type of locators.
 *
 */
export type LocatorType = 0 | 1 | 2;
export type CIMLocator = CIMLocator1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
