/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMLayerTemplate = CIMObject & {
  /**
   * Gets or sets the layer template ID.
   */
  layerTemplateId?: null | string;
  /**
   * Gets or sets the layer template parameters.
   */
  parameters?: null | {
    [k: string]: unknown;
  };
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
