/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMLayerAction = CIMLayerAction1[];

/**
 * Represents a layer action.
 *
 */
export interface CIMLayerAction1 {
  /**
   * Gets or sets the name.
   */
  name?: null | string;
  /**
   * Gets or sets activities.
   */
  activities?: CIMActivity[] | null;
  /**
   * Gets or sets conditions.
   */
  conditions?: CIMCondition[] | null;
}
/**
 * Represents activity.
 *
 */
export interface CIMActivity {}
/**
 * Represents a condition.
 */
export interface CIMCondition {}
