/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines the URI and required field properties for the Indoors Level layer required for floor filtering operations.
 */
export interface CIMLevelLayerProperties {
  /**
   * Gets or sets the URI for the Indoors Level layer in the map CIM.
   */
  layerURI?: null | string;
  /**
   * Gets or sets the sublayer ID when the Level layer is a sublayer within a dynamic map service layer.
   */
  subLayerID?: number;
  /**
   * Gets or sets the name of the field containing the facility id (a foreign key back to the Facility feature class).
   */
  facilityIDField?: null | string;
  /**
   * Gets or sets the name of the field containing the level id.
   */
  levelIDField?: null | string;
  /**
   * Gets or sets the name of the field containing the level "short" name.
   */
  shortNameField?: null | string;
  /**
   * Gets or sets the name of the field containing the level "long" name.
   */
  longNameField?: null | string;
  /**
   * Gets or sets the name of the field containing the level number.
   */
  levelNumberField?: null | string;
  /**
   * Gets or sets the name of the field containing the vertical order for the level.
   */
  verticalOrderField?: null | string;
}
