/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMLinkChartViewport = CIMObject & {
  /**
   * Gets or sets the center X coordinate in the world coordinate system.
   */
  centerX?: number;
  /**
   * Gets or sets the center Y coordinate in the world coordinate system.
   */
  centerY?: number;
  /**
   * Gets or sets the zoom level.
   */
  zoomLevel?: number;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
