/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMLayerAction1 = CIMObject & {
  /**
   * Gets or sets the name.
   */
  name?: null | string;
  /**
   * Gets or sets activities.
   */
  activities?: CIMActivity[] | null;
  /**
   * Gets or sets conditions.
   */
  conditions?: CIMCondition[] | null;
};
export type CIMActivity = CIMObject;
export type CIMCondition = CIMObject;
export type CIMLayerAction = CIMLayerAction1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
