/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The Map series object represents a means to create multi-page PDF or
 * based off of fields in the index layer.
 */
export interface CIMMapSeries {
  /**
   * Gets or sets a value indicating whether the map series is enabled on the layout.
   */
  enabled?: boolean;
  /**
   * Gets or sets the URI of the MapFrame to which MapSeries is linked.
   */
  mapFrameName?: null | string;
  /**
   * Gets or sets the starting page number.
   */
  startingPageNumber?: number;
  /**
   * Gets or sets the current page Id.
   */
  currentPageID?: number;
}
