/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMMapTimeDisplay = CIMObject & {
  /**
   * Gets or sets the current time extent.
   */
  currentTimeExtent?: null | TimeExtent;
  /**
   * Gets or sets the default time interval.
   */
  defaultTimeInterval?: number;
  /**
   * Gets or sets the default time interval units.
   */
  defaultTimeIntervalUnits?: EsriTimeUnits;
  /**
   * Gets or sets the default time window.
   */
  defaultTimeWindow?: number;
  /**
   * Gets or sets the full time extent.
   */
  fullTimeExtent?: null | TimeExtent;
  /**
   * Gets or sets the time reference.
   */
  timeReference?: null | TimeReference;
  /**
   * Gets or sets the time value.
   */
  timeValue?: null | TimeValue;
  /**
   * Gets or sets a value indicating whether or not this map has live data.
   */
  hasLiveData?: boolean;
  /**
   * Gets or sets the time relation.
   */
  timeRelation?: EsriTimeRelation;
  /**
   * Gets or sets a cached set of unique OLE date values.  Expected to be in the CIMMapTimeDisplay's TimeReference.
   */
  uniqueTimes?: number[] | null;
};
export type TimeExtent = TimeValue & {
  /**
   * Gets or sets the start time of the extent.
   */
  startTime?: string;
  /**
   * Gets or sets the end time of the extent.
   */
  endTime?: string;
  /**
   * Gets or sets a value indicating if the time extent is empty.
   */
  empty?: boolean;
  /**
   * Gets or sets a value indicating if the extent contains a start time. If false the time extent has no lower bound.
   */
  startTimeSpecified?: boolean;
  /**
   * Gets or sets a value indicating if the extent contains an end time. If false the time extent has no upper bound.
   */
  endTimeSpecified?: boolean;
};
export type TimeValue = CIMObject & {
  /**
   * Gets or sets the time zone definition of the time.
   */
  timeReference?: null | TimeReference;
};
export type TimeReference = CIMObject & {
  /**
   * Gets or sets the windows id for the time zone.
   */
  timeZoneNameID?: null | string;
  /**
   * Gets or sets a value indicating if the time reference should honor daylight savings time.
   */
  respectsDaylightSavingTime?: boolean;
  /**
   * Gets or sets a value indicating if the time reference should respect dynamic rules for adjusting with daylight savings time for specific years.
   */
  respectsDynamicAdjustmentRules?: boolean;
};
/**
 * Time units.
 */
export type EsriTimeUnits = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
/**
 * Time relation types.
 */
export type EsriTimeRelation = 0 | 1 | 2 | 3;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
