/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMNetworkSourceDisplayFilter = CIMNetworkSourceDisplayFilter1[];

/**
 * Represents a network source display filter.
 *
 */
export interface CIMNetworkSourceDisplayFilter1 {
  /**
   * Gets or sets the network source.
   */
  networkSource?: null | string;
  /**
   * Gets or sets a value indicating whether the filter is visible.
   */
  visible?: boolean;
  /**
   * Gets or sets the definition expression.
   */
  definitionExpression?: null | string;
}
