/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMNetworkTraceConfiguration1 = CIMObject & {
  /**
   * Gets or sets the name of trace configuration.
   */
  name?: null | string;
  /**
   * Gets or sets global id of trace configuration.
   */
  id?: null | string;
};
export type CIMNetworkTraceConfiguration = CIMNetworkTraceConfiguration1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
