/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMNetworkAttributeParameterDefinitionValue1 = CIMObject & {
  /**
   * Gets or sets the network attribute name.
   */
  networkAttributeName?: null | string;
  /**
   * Gets or sets the network parameter name.
   */
  networkParameterName?: null | string;
  /**
   * Gets or sets a value indicating whether this is a restriction usage type network parameter.
   */
  isRestrictionUsage?: boolean;
  /**
   * Gets or sets the value type. Supports: Short, Long, Float, Double, Date, String, Bool.
   */
  valueType?: ValueType;
  value?: unknown;
};
/**
 * The data type of a value.
 */
export type ValueType = 2 | 3 | 4 | 5 | 7 | 8 | 11;
export type CIMNetworkAttributeParameterDefinitionValue = CIMNetworkAttributeParameterDefinitionValue1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
