/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMNetworkDiagramDataConnection = CIMDataConnection & {
  /**
   * Gets or sets the workspace connection string.
   */
  workspaceConnectionString?: null | string;
  /**
   * Gets or sets the workspace factory.
   */
  workspaceFactory?: WorkspaceFactory;
  /**
   * Gets or sets the classID of the custom workspace factory.
   */
  customWorkspaceFactoryCLSID?: null | string;
  /**
   * Gets or sets the dataset name.
   */
  dataset?: null | string;
  /**
   * Gets or sets the dataset type.
   */
  datasetType?: EsriDatasetType;
  /**
   * Gets or sets feature dataset.
   */
  featureDataset?: null | string;
  /**
   * Gets or sets the diagram.
   */
  diagram?: null | string;
  /**
   * Gets or sets a value indicating whether or not the diagram is stored.
   */
  isStored?: boolean;
  /**
   * Gets or sets the diagram table name.
   */
  table?: null | string;
};
export type CIMDataConnection = CIMObject;
/**
 * Workspace factory types.
 *
 */
export type WorkspaceFactory =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 21
  | 22
  | 23
  | 24
  | 25;
/**
 * Dataset type constants.
 */
export type EsriDatasetType =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 31
  | 32
  | 33
  | 34
  | 35
  | 36
  | 37
  | 38
  | 39
  | 40
  | 41;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
