/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specified how features are drawn.
 */
export type Object3DRenderingMode = 0 | 1;
export type CIMObject3DRenderingFilter = CIMObject3DRenderingFilter1[];

/**
 * Represents a 3D object rendering filter.
 */
export interface CIMObject3DRenderingFilter1 {
  /**
   * Gets or sets the ID.
   */
  id?: null | string;
  /**
   * Gets or sets the name.
   */
  name?: null | string;
  /**
   * Gets or sets the description.
   */
  description?: null | string;
  /**
   * Gets or sets the filter blocks.
   */
  filterBlocks?: CIMObject3DRenderingFilterBlock[] | null;
  /**
   * Gets or sets the authoring info.
   */
  authoringInfo?: null | CIMObject3DRenderingFilterAuthoringInfo;
}
/**
 * Represents a 3D object rendering filter block.
 */
export interface CIMObject3DRenderingFilterBlock {
  /**
   * Gets or sets the title.
   */
  title?: null | string;
  /**
   * Gets or sets the rendering mode.
   */
  mode?: Object3DRenderingMode;
  /**
   * Gets or sets the expression.
   */
  expression?: null | string;
}
/**
 * Represents a filter authoring info.
 */
export interface CIMObject3DRenderingFilterAuthoringInfo {
  /**
   * Gets or sets a value indicating whether the filter is displayed in the UI or not.
   */
  isVisible?: boolean;
  /**
   * Gets or sets the filter blocks.
   */
  filterBlocks?: CIMObject3DRenderingFilterBlockAuthoringInfo[] | null;
}
/**
 * Represents a filter block authoring info.
 */
export interface CIMObject3DRenderingFilterBlockAuthoringInfo {
  /**
   * Gets or sets the filter state.
   */
  filterStates?: CIMObject3DRenderingFilterState[] | null;
}
/**
 * Represents a 3D object rendering filter value.
 */
export interface CIMObject3DRenderingFilterState {
  /**
   * Gets or sets the filter type.
   */
  filterType?: null | string;
  /**
   * Gets or sets the selected values.
   */
  selectedValues?: string[] | null;
}
