/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a grid layout for pop-up media infos.
 *
 */
export interface CIMPopupLayout {
  /**
   * Gets or sets the array of column width values in percentage of the table width (0-100).
   */
  columnWidths?: number[] | null;
  /**
   * Gets or sets the border width in points.
   */
  borderWidth?: number;
  /**
   * Gets or sets the border color.
   */
  borderColor?: null | CIMColor;
}
/**
 * Supports colors in the CIM model by providing low level access to properties common amongst all color types.
 */
export interface CIMColor {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
}
/**
 * Supports colors spaces by providing a common base type for all color spaces.
 */
export interface CIMColorSpace {}
