/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMPointCloudFilter1 = CIMObject & {
  /**
   * Gets or sets the field used for the filter.
   */
  field?: null | string;
};
export type CIMPointCloudFilter = CIMPointCloudFilter1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
