/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Visual variable info types.
 *
 */
export type ExpressionReturnType = 0 | 1 | 2;
/**
 * Time units.
 */
export type EsriTimeUnits = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * Represents pop-up info.
 *
 */
export interface CIMPopupInfo {
  /**
   * Gets or sets the title.
   */
  title?: null | string;
  /**
   * Gets or sets Arcade expressions that are referenced as fields in one or more elements in MediaInfos.
   */
  expressionInfos?: CIMExpressionInfo[] | null;
  /**
   * Gets or sets the media infos.
   */
  mediaInfos?: CIMMediaInfo[] | null;
  /**
   * Gets or sets the field name and the sort order by which the related records will be ordered.
   * The items are defined by the related field name (Format: RelationshipName\\FieldName) as the Keys and the sort order (Enum: Asc, Desc) as the Values.
   */
  relatedRecordSortOrder?: CIMStringMap[] | null;
  /**
   * Gets or sets the grid layout for the media infos.
   */
  gridLayout?: null | CIMPopupLayout;
  /**
   * Gets or sets the pop-up field descriptions.
   */
  fieldDescriptions?: CIMPopupFieldDescription[] | null;
}
/**
 * Represents the properties required for authoring an Arcade expression.
 */
export interface CIMExpressionInfo {
  /**
   * Gets or sets the human readable text that describes the expression.
   */
  title?: null | string;
  /**
   * Gets or sets the Arcade expression used to evaluate and return the value that a property expects.
   */
  expression?: null | string;
  /**
   * Gets or sets the Name of the expression.
   */
  name?: null | string;
  /**
   * Gets or sets the ReturnType of the expression.
   */
  returnType?: ExpressionReturnType;
}
/**
 * Represents media info.
 *
 */
export interface CIMMediaInfo {
  /**
   * Gets or sets the row.
   */
  row?: number;
  /**
   * Gets or sets the column.
   */
  column?: number;
  /**
   * Gets or sets the amount of time in RefreshRateUnit to wait between refreshing the media info.
   */
  refreshRate?: number;
  /**
   * Gets or sets the units for the amount of time to wait between refreshing the media.
   */
  refreshRateUnit?: EsriTimeUnits;
  /**
   * Gets or sets the row span.
   */
  rowSpan?: number;
  /**
   * Gets or sets the column span.
   */
  columnSpan?: number;
}
/**
 * Represents a string map of key value pairs.
 *
 */
export interface CIMStringMap {
  /**
   * Gets or sets the key.
   */
  key?: null | string;
  /**
   * Gets or sets the value.
   */
  value?: null | string;
}
/**
 * Represents a grid layout for pop-up media infos.
 *
 */
export interface CIMPopupLayout {
  /**
   * Gets or sets the array of column width values in percentage of the table width (0-100).
   */
  columnWidths?: number[] | null;
  /**
   * Gets or sets the border width in points.
   */
  borderWidth?: number;
  /**
   * Gets or sets the border color.
   */
  borderColor?: null | CIMColor;
}
/**
 * Supports colors in the CIM model by providing low level access to properties common amongst all color types.
 */
export interface CIMColor {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
}
/**
 * Supports colors spaces by providing a common base type for all color spaces.
 */
export interface CIMColorSpace {}
/**
 * Represents a pop-up field description.
 *
 */
export interface CIMPopupFieldDescription {
  /**
   * Gets or sets the field alias.
   */
  alias?: null | string;
  /**
   * Gets or sets the field name.
   */
  fieldName?: null | string;
  /**
   * Gets or sets the number format.
   */
  numberFormat?: null | CIMNumberFormat;
}
/**
 * Represents a number format.
 *
 */
export interface CIMNumberFormat {}
