/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Point cloud shape types.
 *
 */
export type PointCloudShapeType = 0 | 1;
/**
 * Point cloud field transform types.
 *
 */
export type PointCloudFieldTransformType = 0 | 1 | 2 | 3 | 4;

/**
 * Represents a point cloud renderer.
 */
export interface CIMPointCloudRenderer {
  /**
   * Gets or sets the symbol type.
   */
  pointShape?: PointCloudShapeType;
  /**
   * Gets or sets the algorithm used to determine the symbol size.
   */
  pointSizeAlgorithm?: null | CIMPointCloudAlgorithm;
  /**
   * Gets or sets the filter used to filter the points being drawn.
   */
  colorModulation?: null | CIMColorModulationInfo;
  /**
   * Gets or sets the field transform type.
   */
  fieldTransformType?: PointCloudFieldTransformType;
  /**
   * Gets or sets the field used to render the points.
   */
  field?: null | string;
}
/**
 * Represents a point cloud algorithm.
 */
export interface CIMPointCloudAlgorithm {}
/**
 * Indicates whether modulation should be used to render the point. Low modulation values will darken the point color.
 */
export interface CIMColorModulationInfo {
  /**
   * Gets or sets the attribute to use as a source for the color modulation.
   */
  field?: null | string;
  /**
   * Gets or sets the minimum value to compute modulation on linear scale based on field value.
   */
  minValue?: number;
  /**
   * Gets or sets the maximum value to compute modulation on linear scale based on field value.
   */
  maxValue?: number;
}
