/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMPostprocessingEffect = CIMPostprocessingEffect1[];

/**
 * Represents a post-processing effect definition to be applied to a 3D view.
 */
export interface CIMPostprocessingEffect1 {
  /**
   * Gets or sets a value indicating whether the effect should be applied to the scene.
   */
  isActive?: boolean;
}
