/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMPopupFieldDescription1 = CIMObject & {
  /**
   * Gets or sets the field alias.
   */
  alias?: null | string;
  /**
   * Gets or sets the field name.
   */
  fieldName?: null | string;
  /**
   * Gets or sets the number format.
   */
  numberFormat?: null | CIMNumberFormat;
};
export type CIMNumberFormat = CIMObject;
export type CIMPopupFieldDescription = CIMPopupFieldDescription1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
