/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Relationship Cardinality.
 */
export type EsriRelCardinality = 0 | 1 | 2;
export type CIMRelateInfoBase = CIMRelateInfoBase1[];

/**
 * Represents relate base.
 *
 */
export interface CIMRelateInfoBase1 {
  /**
   * Gets or sets the relate data connection.
   */
  dataConnection?: null | CIMDataConnection;
  /**
   * Gets or sets the foreign key.
   */
  foreignKey?: null | string;
  /**
   * Gets or sets the primary key.
   */
  primaryKey?: null | string;
  /**
   * Gets or sets the relate cardinality.
   */
  cardinality?: EsriRelCardinality;
  /**
   * Gets or sets the name.
   */
  name?: null | string;
}
/**
 * Represents a data connection.
 */
export interface CIMDataConnection {}
