/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMRenderingRule = CIMObject & {
  /**
   * Gets or sets the rendering rule description.
   */
  description?: null | string;
  /**
   * Gets or sets the rendering rule name.
   */
  name?: null | string;
  /**
   * Gets or sets the rendering rule variable name.
   */
  variableName?: null | string;
  /**
   * Gets or sets the rendering rule arguments as a property set.
   */
  arguments?: null | {
    [k: string]: unknown;
  };
  /**
   * Gets or sets the rendering rule definition.
   */
  definition?: null | string;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
