/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMRasterColorCorrection = CIMObject & {
  /**
   * Gets or sets the pre-stretch type of color correction.
   */
  preStretchType?: ColorCorrectionStretchType;
  /**
   * Gets or sets the color balance method.
   */
  colorBalanceMethod?: ColorBalanceMethod;
  /**
   * Gets or sets the color matching method.
   */
  colorMatchingMethod?: ColorMatchingMethod;
  /**
   * Gets or sets a value indicating whether or not contrast adjustment is needed.
   */
  needContrastAdjustment?: boolean;
  /**
   * Gets or sets the target color surface type.
   */
  targetColorSurfaceType?: TargetColorSurfaceType;
  /**
   * Gets or sets the target color raster.
   */
  targetColorRaster?: null | CIMDataConnection;
  /**
   * Gets or sets a value indicating whether or not this is a user defined reference.
   */
  userDefinedReference?: boolean;
  /**
   * Gets or sets the reference OID.
   */
  referenceOID?: number;
};
/**
 * A list of color correction stretch types.
 */
export type ColorCorrectionStretchType = 0 | 1 | 2 | 3;
/**
 * A list of color balance methods.
 */
export type ColorBalanceMethod = 0 | 1 | 2 | 3;
/**
 * A list of color matching methods.
 */
export type ColorMatchingMethod = 0 | 1 | 2 | 3;
/**
 * Target color surface type.
 *
 */
export type TargetColorSurfaceType = 0 | 1 | 2 | 3 | 4;
export type CIMDataConnection = CIMObject;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
