/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMRasterColorizerMapping1 = CIMObject & {
  /**
   * Gets or sets the Object ID of the raster in the raster catalog.
   */
  rasterOID?: number;
  /**
   * Gets or sets the index of the colorizer.
   */
  colorizerIndex?: number;
};
export type CIMRasterColorizerMapping = CIMRasterColorizerMapping1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
