/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMRasterDimensionalDefinition1 = CIMObject & {
  /**
   * Gets or sets the name of the variable.
   */
  variableName?: null | string;
  /**
   * Gets or sets the name of the dimension.
   */
  dimensionName?: null | string;
  /**
   * Gets or sets the minimum dimension values.
   */
  minimumValues?: number[] | null;
  /**
   * Gets or sets the maximum dimension values.
   */
  maximumValues?: number[] | null;
};
export type CIMRasterDimensionalDefinition = CIMRasterDimensionalDefinition1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
