/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Raster resampling types.
 */
export type RasterResamplingType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
export type CIMRasterColorizer = CIMRasterColorizer1[];

/**
 * Represents a raster colorizer.
 *
 */
export interface CIMRasterColorizer1 {
  /**
   * Gets or sets the raster resampling type.
   */
  resamplingType?: RasterResamplingType;
  /**
   * Gets or sets the contrast value.
   */
  contrast?: number;
  /**
   * Gets or sets the brightness value.
   */
  brightness?: number;
  /**
   * Gets or sets the no data color.
   */
  noDataColor?: null | CIMColor;
}
/**
 * Supports colors in the CIM model by providing low level access to properties common amongst all color types.
 */
export interface CIMColor {
  /**
   * Gets and sets alpha.
   */
  alpha?: number;
  /**
   * Gets or sets the color spaced used defined by an ICC color profile.
   */
  colorSpace?: null | CIMColorSpace;
  /**
   * Gets or sets the values for the color and alpha channels as defined by the color model. Alpha is the last value in the array for all colors.
   */
  values?: number[] | null;
}
/**
 * Supports colors spaces by providing a common base type for all color spaces.
 */
export interface CIMColorSpace {}
