/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines the URI and required field properties for the Indoors Site layer required for floor filtering operations.
 */
export interface CIMSiteLayerProperties {
  /**
   * Gets or sets the URI for the Indoors Site layer in the map CIM.
   */
  layerURI?: null | string;
  /**
   * Gets or sets the sublayer ID when the Site layer is a sublayer within a dynamic map service layer.
   */
  subLayerID?: number;
  /**
   * Gets or sets the name of the field containing the site id.
   */
  siteIDField?: null | string;
  /**
   * Gets or sets the name of the field containing the site name.
   */
  nameField?: null | string;
}
