/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMSymbolLayerMasking = CIMSymbolLayerMasking1[];

/**
 * Represents symbol layer masking.
 *
 */
export interface CIMSymbolLayerMasking1 {
  /**
   * Gets or sets the symbol layer identifiers.
   */
  symbolLayers?: CIMSymbolLayerIdentifier[] | null;
}
/**
 * Represents symbol layer identifier.
 *
 */
export interface CIMSymbolLayerIdentifier {
  /**
   * Gets or sets the symbol layer name.
   */
  symbolLayerName?: null | string;
}
