/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMSymbolIdentifier = CIMSymbolIdentifier1[];

/**
 * Represents a symbol identifier.
 *
 */
export interface CIMSymbolIdentifier1 {
  /**
   * Gets or sets the ID which identifies the symbol in the collection.
   */
  id?: number;
  /**
   * Gets or sets the name of the symbol in the symbol collection.
   */
  name?: null | string;
  /**
   * Gets or sets the symbol.
   */
  symbol?: null | CIMSymbol;
}
/**
 * Represents a symbol. A symbol is used to describe how a geometric shape, such as that from a graphic or feature, is displayed.
 *
 */
export interface CIMSymbol {}
