/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a service connection.
 *
 */
export interface CIMServiceConnection {
  /**
   * Gets or sets the description.
   */
  description?: null | string;
}
