/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMSymbolIdentifier1 = CIMObject & {
  /**
   * Gets or sets the ID which identifies the symbol in the collection.
   */
  id?: number;
  /**
   * Gets or sets the name of the symbol in the symbol collection.
   */
  name?: null | string;
  /**
   * Gets or sets the symbol.
   */
  symbol?: null | CIMSymbol;
};
export type CIMSymbol = CIMObject;
export type CIMSymbolIdentifier = CIMSymbolIdentifier1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
