/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMSymbolLayerIdentifier = CIMSymbolLayerIdentifier1[];

/**
 * Represents symbol layer identifier.
 *
 */
export interface CIMSymbolLayerIdentifier1 {
  /**
   * Gets or sets the symbol layer name.
   */
  symbolLayerName?: null | string;
}
