/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMSymbolLayerDrawing = CIMObject & {
  /**
   * Gets or sets the symbol layer identifiers.
   */
  symbolLayers?: CIMSymbolLayerIdentifier[] | null;
  /**
   * Gets or sets a value indicating whether symbol layer drawing is enabled.
   */
  useSymbolLayerDrawing?: boolean;
};
export type CIMSymbolLayerIdentifier = CIMObject & {
  /**
   * Gets or sets the symbol layer name.
   */
  symbolLayerName?: null | string;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
