/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMScale1 = CIMObject & {
  /**
   * Gets or sets the  numeric value representing the 2D scale or 3D distance.
   */
  value?: number;
  /**
   * Gets or sets the string value for the alias name of the Scale.
   */
  alias?: null | string;
};
export type CIMScale = CIMScale1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
