/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMTinRenderer = CIMTinRenderer1[];

/**
 * Represents a TIN renderer.
 *
 */
export interface CIMTinRenderer1 {
  /**
   * Gets or sets a value indicating whether or not to illuminate.
   */
  illuminate?: boolean;
}
