/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a time table definition.
 *
 */
export interface CIMTimeTableDefinition {
  /**
   * Gets or sets the start time field.
   */
  startTimeField?: null | string;
  /**
   * Gets or sets the end time field.
   */
  endTimeField?: null | string;
  /**
   * Gets or sets the time value format.
   */
  timeValueFormat?: null | string;
  /**
   * Gets or sets the track ID field.
   */
  trackIDField?: null | string;
}
