/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMTimeDisplayDefinition = CIMObject & {
  /**
   * Gets or sets a value indicating whether time is cumulative.
   */
  cumulative?: boolean;
  /**
   * Gets or sets the time interval.
   */
  timeInterval?: number;
  /**
   * Gets or sets the time interval units.
   */
  timeIntervalUnits?: EsriTimeUnits;
  /**
   * Gets or sets the time offset.
   */
  timeOffset?: number;
  /**
   * Gets or sets the time offset units.
   */
  timeOffsetUnits?: EsriTimeUnits;
  /**
   * Gets or sets a cached set of unique OLE date values.
   */
  uniqueTimes?: number[] | null;
};
/**
 * Time units.
 */
export type EsriTimeUnits = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
