/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMTimeDimensionDefinition = CIMObject & {
  /**
   * Gets or sets the time dimension name.
   */
  timeDimensionName?: null | string;
  /**
   * Gets or sets the time dimension format.
   */
  timeDimensionFormat?: null | string;
};

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
