/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMVideoDataConnection = CIMDataConnection & {
  /**
   * Gets or sets the URI of the video files.
   */
  uri?: null | string;
};
export type CIMDataConnection = CIMObject;

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
