/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMVideoTimelineRangeIndicator = CIMVideoTimelineRangeIndicator1[];

/**
 * Represents a range indicator on a video timeline.
 */
export interface CIMVideoTimelineRangeIndicator1 {
  /**
   * Gets or sets the indicator label.
   */
  label?: null | string;
  /**
   * Gets or sets the elapsed time from the beginning of the video in ticks for the minimum time in the range.
   */
  minimum?: number;
  /**
   * Gets or sets the elapsed time from the beginning of the video in ticks for the maximum time in the range.
   */
  maximum?: number;
}
