/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a visual effect definition for stylized rendering of all the content in a map or scene.
 */
export interface CIMVisualEffect {
  /**
   * Gets or sets a value indicating whether the effect should be applied to the scene.
   */
  isActive?: boolean;
}
