/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CIMVideoTimelineRangeIndicator1 = CIMVideoTimelineIndicator & {
  /**
   * Gets or sets the elapsed time from the beginning of the video in ticks for the minimum time in the range.
   */
  minimum?: number;
  /**
   * Gets or sets the elapsed time from the beginning of the video in ticks for the maximum time in the range.
   */
  maximum?: number;
};
export type CIMVideoTimelineIndicator = CIMObject & {
  /**
   * Gets or sets the indicator label.
   */
  label?: null | string;
};
export type CIMVideoTimelineRangeIndicator = CIMVideoTimelineRangeIndicator1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
