/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Workspace factory types.
 *
 */
export type WorkspaceFactory =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 21
  | 22
  | 23
  | 24
  | 25;

/**
 * Represents a workspace connection.
 *
 */
export interface CIMWorkspaceConnection {
  /**
   * Gets or sets the workspace connection string.
   */
  workspaceConnectionString?: null | string;
  /**
   * Gets or sets the workspace factory.
   */
  workspaceFactory?: WorkspaceFactory;
  /**
   * Gets or sets the classID of the custom workspace factory.
   */
  customWorkspaceFactoryCLSID?: null | string;
}
