/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines the capture mode used to specify new Z values when creating or modifying features.
 */
export type EditingElevationCaptureMode = 0 | 1 | 2;
