/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Policy on when to return the from-edge in the network forward star adjacencies object.
 */
export type EsriNetworkForwardStarBacktrack = 0 | 1 | 2 | 3;
