/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents the rank or "level" at which the layer participates in filtering for Indoors or floor-aware layers.
 */
export type FloorFilterRank = 0 | 1 | 2 | 3;
