/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NAAgent1 = NAAgentDefinition & {};
export type NAAgentDefinition = CIMObject;
export type NAAgent = NAAgent1[];

/**
 * Represents the base CIM object class.
 *
 */
export interface CIMObject {}
