/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NAAttributeParameterValue = NAAttributeParameterValue1[];

/**
 * Represents a network attribute parameter value. This class is reserved for esri internal use only.
 */
export interface NAAttributeParameterValue1 {
  /**
   * Gets and sets the attribute name.
   */
  attributeName?: null | string;
  /**
   * Gets and sets the parameter names.
   */
  parameterName?: null | string;
  /**
   * Gets and sets the variant type.
   */
  varType?: number;
  value?: unknown;
}
