/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a network travel mode. This class is reserved for esri internal use only.
 */
export interface NetworkTravelMode {
  /**
   * Gets and sets the name.
   */
  name?: null | string;
  /**
   * Gets and sets the type.
   */
  type?: null | string;
  /**
   * Gets and sets the description.
   */
  description?: null | string;
  /**
   * Gets and sets the impedance attribute name.
   */
  impedanceAttributeName?: null | string;
  /**
   * Gets and sets the time attribute name.
   */
  timeAttributeName?: null | string;
  /**
   * Gets and sets the distance attribute name.
   */
  distanceAttributeName?: null | string;
  /**
   * Gets and sets the restriction attribute name.
   */
  restrictionAttributeNames?: string[] | null;
  /**
   * Gets and sets the attribute parameter values.
   */
  attributeParameterValues?: NetworkTravelModeParameterValue[] | null;
  /**
   * Gets and sets a boolean indicating whether or not to use the hierarchy.
   */
  useHierarchy?: boolean;
  /**
   * Gets and sets a setting which indicates how U-Turns should be restricted in the analysis as a string.
   */
  uturnAtJunctions?: null | string;
  /**
   * Gets and sets the output geometry precision.
   */
  simplificationTolerance?: null | number;
  /**
   * Gets and sets the output geometry precision units as a string.
   */
  simplificationToleranceUnits?: null | string;
}
/**
 * Represents a network travel mode parameter value. This class is reserved for esri internal use only.
 */
export interface NetworkTravelModeParameterValue {
  /**
   * Gets and sets the attribute name.
   */
  attributeName?: null | string;
  /**
   * Gets and sets the parameter name.
   */
  parameterName?: null | string;
  value?: unknown;
}
