/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The source type of the travel mode used by the travel mode context.
 */
export type NetworkTravelModeSourceType = 0 | 1 | 2;
