/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Raster mosaic methods.
 *
 */
export type RasterMosaicMethod = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;
